steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/odin-web:$SHORT_SHA
  - -t
  - gcr.io/$PROJECT_ID/odin-web:latest
  - .
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/odin-web:$SHORT_SHA
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/odin-web:latest
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - $_DEPLOYMENT
  - "*=gcr.io/$PROJECT_ID/odin-web:$SHORT_SHA"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
images:
- gcr.io/$PROJECT_ID/odin-web:$SHORT_SHA

